spring.application.name=ems-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/emsdb
spring.datasource.username=postgres
spring.datasource.password=4321
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA ────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=update